testpr1

diff --git a/.github/workflows/deploy-pr.yml b/.github/workflows/deploy-pr.yml
--- a/.github/workflows/deploy-pr.yml
+++ b/.github/workflows/deploy-pr.yml
@@ -34,13 +34,14 @@ jobs:
 
                 echo "BRANCH_NAME=$BRANCH_NAME"
                 echo "PORT=$PORT"
-
+                export PORT=$PORT
+                export BRANCH_NAME=$BRANCH_NAME
 
                 pm2 describe onlyfriends-$BRANCH_NAME > /dev/null 2>&1
                 if [ $? -eq 0 ]; then
                   pm2 restart onlyfriends-$BRANCH_NAME
                 else
-                  PORT=$PORT BRANCH_NAME=$BRANCH_NAME pm2 start ecosystem.config.js --env development --update-env || { echo "PM2 start failed"; pm2 logs; exit 1; }
+                  pm2 start ecosystem.config.js --env development --update-env || { echo "PM2 start failed"; pm2 logs; exit 1; }
                 fi
                 
                 # Add route to rprox
